"""empty message

Revision ID: 07b81e759ffc
Revises: c35195ef3c18
Create Date: 2020-04-20 14:57:10.925055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b81e759ffc'
down_revision = 'c35195ef3c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_tags',
    sa.Column('grant_tag_id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['grant_tag_id'], ['grant_tag.id'], ),
    sa.PrimaryKeyConstraint('grant_tag_id', 'grant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_tags')
    op.drop_table('grant_tag')
    # ### end Alembic commands ###
