"""Add images JSON field to Product

Revision ID: 3d0d38c44cd5
Revises: 9d9d0ba508ab
Create Date: 2020-04-25 21:59:22.147720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d0d38c44cd5'
down_revision = '9d9d0ba508ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'images')
    # ### end Alembic commands ###
