"""Funds, deadline optional

Revision ID: 9502972f3c57
Revises: 1ba2b76dfead
Create Date: 2020-04-27 21:10:04.766720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9502972f3c57'
down_revision = '1ba2b76dfead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grants', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('grants', 'funds',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grants', 'funds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grants', 'deadline',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
