"""empty message

Revision ID: 962c69db1dc7
Revises: 07b81e759ffc
Create Date: 2020-04-20 16:22:54.744014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962c69db1dc7'
down_revision = '07b81e759ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'grant_tag', ['text'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grant_tag', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
