"""Fix typo in table name, add thumbnail fields to Product

Revision ID: 9d9d0ba508ab
Revises: d1f54629a70b
Create Date: 2020-04-25 21:21:31.830869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9d0ba508ab'
down_revision = 'd1f54629a70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_category_id', 'product_id')
    )
    op.drop_table('procuct_categories')
    op.add_column('product', sa.Column('thumbnail_bucket', sa.String(), nullable=True))
    op.add_column('product', sa.Column('thumbnail_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'thumbnail_key')
    op.drop_column('product', 'thumbnail_bucket')
    op.create_table('procuct_categories',
    sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], name='procuct_categories_product_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='procuct_categories_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_category_id', 'product_id', name='procuct_categories_pkey')
    )
    op.drop_table('product_categories')
    # ### end Alembic commands ###
